test: &default

  # Credentials for REST APIs
  client_id: AbjSEwYLL1Dg-hr43iCwJKxUNbqmwFN0H2YtXSWJCxWh6O3uWtvgQP3bY3sMg9UkjmV3_IGt3RSsbTyR
  client_secret: EJKJNwnXb28obs-DgtO8pvqaja9g2jWdvb8K5PQTCTJZPEr7mW61xoNSlKyrhvEHnrcTPtpUC6NHW3ZR

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: fabrizio.machella-merchant@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
  app_id: APP-6C058157VJ843715Y